<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (c) 2012 NVIDIA Corporation.  All Rights Reserved.

     NVIDIA Corporation and its licensors retain all intellectual property and
     proprietary rights in and to this software and related documentation.  Any
     use, reproduction, disclosure or distribution of this software and related
     documentation without an express license agreement from NVIDIA Corporation
     is strictly prohibited.
 */
-->
<!DOCTYPE AudioConfigs [
  <!ELEMENT AudioConfigs (alsa_device)>
  <!ELEMENT alsa_device (pcm_config, playback, capture, voice-call)>
  <!ELEMENT playback (pcm_config, device, path)>
  <!ELEMENT capture (pcm_config, device, path)>
  <!ELEMENT voice-call (pcm_config, device, path)>
  <!ELEMENT device (path)>
  <!ELEMENT path (ctl)>
  <!ELEMENT alsa_device EMPTY>
  <!ATTLIST alsa_device name (music|voice|aux|voice-call|bt-voice-call) #REQUIRED>
  <!ATTLIST alsa_device card_id CDATA #REQUIRED>
  <!ATTLIST alsa_device card_name CDATA #REQUIRED>
  <!ATTLIST alsa_device device_id CDATA #REQUIRED>
  <!ELEMENT alsa_device EMPTY>
  <!ELEMENT pcm_config EMPTY>
  <!ATTLIST pcm_config rate (8000|11025|16000|22050|32000|44100|48000|64000|88200|96000|176400|192000) #IMPLIED>
  <!ATTLIST pcm_config channels (1|2|3|4|5|6|7|8) #IMPLIED>
  <!ATTLIST pcm_config bps (16|32) #IMPLIED>
  <!ATTLIST pcm_config period_size CDATA #IMPLIED>
  <!ATTLIST pcm_config period_count CDATA #IMPLIED>
  <!ATTLIST pcm_config start_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config stop_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config silence_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config avail_min CDATA #IMPLIED>
  <!ELEMENT pcm_config EMPTY>
  <!ELEMENT device EMPTY>
  <!ATTLIST device name (speaker|headphone|earpiece|bt-sco|aux|builtin-mic|headset-mic|bt-sco-mic|voice-call|bt-voice-call) #REQUIRED>
  <!ELEMENT device EMPTY>
  <!ELEMENT path EMPTY>
  <!ATTLIST path name CDATA #IMPLIED>
  <!ELEMENT path EMPTY>
  <!ELEMENT param EMPTY>
  <!ATTLIST param name CDATA #REQUIRED>
  <!ATTLIST param val CDATA #REQUIRED>
  <!ELEMENT param EMPTY>
  <!ELEMENT ctl EMPTY>
  <!ATTLIST ctl name CDATA #REQUIRED>
  <!ATTLIST ctl val CDATA #REQUIRED>
  <!ELEMENT ctl EMPTY>
]>
<!--
     This file is used to declare various board specific audio configs
-->

<AudioConfigs>
  <alsa_device name="music"
               card_id="1"
               card_name="tegracodec"
               device_id="0">
    <pcm_config rate="48000"
                channels="2"
                bps="16"
                period_size="1024"
                period_count="4"
                start_threshold="4095"
                stop_threshold="4096"
                silence_threshold="0"
                avail_min="1"/>

    <param name="ulp" val="0"/>

    <path>
      <!-- playback paths-->
      <ctl name="DRC Switch" val="1"/>
      <ctl name="Left Speaker Mixer DACL Switch" val="1"/>
      <ctl name="Right Speaker Mixer DACR Switch" val="1"/>
      <ctl name="Headphone Switch" val="1"/>
      <ctl name="HPF Mode" val="Hi-fi"/>
      <!-- capture paths-->
      <ctl name="Left Input PGA Volume" val="0x1C"/>
      <ctl name="Right Input PGA Volume" val="0x1C"/>
    </path>

    <playback>
      <device name="headphone">
        <path name="on">
          <ctl name="Headphone Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="Int Spk Switch" val="1"/>
          <ctl name="Speaker Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Int Spk Switch" val="0"/>
          <ctl name="Speaker Switch" val="0"/>
        </path>
      </device>
      <device name="dock">
        <path name="on">
          <ctl name="AUX Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="AUX Switch" val="0"/>
        </path>
      </device>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>

      <device name="builtin-mic">
        <path name="on">
          <ctl name="Recording Gain" val="0"/>
          <ctl name="Left Input PGA Common Mode Switch" val="1"/>
          <ctl name="Left Capture Mux" val="Left"/>
          <ctl name="Left Input PGA Switch" val="0"/>
          <ctl name="ADC Input" val="DMIC"/>
          <ctl name="Int Mic Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Int Mic Switch" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="Recording Gain" val="1"/>
          <ctl name="Left Input PGA Common Mode Switch" val="0"/>
          <ctl name="Left Input Inverting Mux" val="IN2L"/>
          <ctl name="Left Input Mux" val="IN1L"/>
          <ctl name="Left Capture Mux" val="Left"/>
          <ctl name="Right Capture Mux" val="Left"/>
          <ctl name="Left Input PGA Switch" val="1"/>
          <ctl name="ADC Input" val="ADC"/>
          <ctl name="Mic Jack Switch" val="1"/>
        </path>
        <path name="off">
		<ctl name="Left Input PGA Common Mode Switch" val="1"/>
		<ctl name="Left Capture Mux" val="Left"/>
          <ctl name="Right Capture Mux" val="Right"/>
		  <ctl name="Left Input PGA Switch" val="0"/>
          <ctl name="Mic Jack Switch" val="0"/>
        </path>
      </device>
    </capture>
  </alsa_device>

  <alsa_device name="voice"
               card_id="1"
               card_name="tegracodec"
               device_id="2">
    <pcm_config rate="8000"
                channels="1"
                bps="16"
                period_size="256"
                period_count="4"
                start_threshold="1023"
                stop_threshold="1024"
                silence_threshold="0"
                avail_min="1"/>
    <playback>
      <device name="bt-sco"/>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="bt-sco-mic"/>
    </capture>
  </alsa_device>

  <alsa_device name ="aux"
             card_id="-1"
             card_name="Tegra"
             device_id="3">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>
    <param name="HW Rates" val="48000 44100"/>
    <playback>
      <device name="aux"/>
    </playback>
  </alsa_device>

<alsa_device name="wfd">
    <pcm_config rate="48000"
                channels="2"
                bps="16"
                period_size="1024"
                period_count="4"/>
    <playback>
      <device name="wfd"/>
    </playback>
</alsa_device>

  <alsa_device name="music"
               card_id="-1"
               card_name="tegrart5640"
               device_id="0">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>
    <playback>
      <device name="headphone">
        <path name="on">
          <ctl name="Headphone Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="Int Spk Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Int Spk Switch" val="0"/>
        </path>
      </device>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="builtin-mic">
        <path name="on">
          <ctl name="Int Mic Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Int Mic Switch" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="Mic Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Mic Jack Switch" val="0"/>
        </path>
      </device>
    </capture>
  </alsa_device>

  <alsa_device name="voice"
               card_id="-1"
               card_name="tegrart5640"
               device_id="2">
    <pcm_config rate="8000"
                channels="1"
                bps="16"
                period_size="256"
                period_count="4"
                start_threshold="1023"
                stop_threshold="1024"
                silence_threshold="0"
                avail_min="1"/>
    <playback>
      <device name="bt-sco"/>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="bt-sco-mic"/>
    </capture>
  </alsa_device>

  <alsa_device name="music"
               card_id="-1"
               card_name="tegramax98095"
               device_id="0">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>
    <path>
      <!-- playback paths-->
      <ctl name="Left Speaker Mixer Left DAC1 Switch" val="1"/>
      <ctl name="Right Speaker Mixer Left DAC1 Switch" val="1"/>
      <ctl name="Left Headphone Mixer Left DAC1 Switch" val="1"/>
      <ctl name="Right Headphone Mixer Left DAC1 Switch" val="1"/>
      <ctl name="Speaker Volume" val="0x15"/>
    </path>

    <playback>
      <device name="headphone">
        <path name="on">
          <ctl name="Headphone Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="Int Spk Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Int Spk Switch" val="0"/>
        </path>
      </device>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="builtin-mic">
        <path name="on">
          <ctl name="Int Mic Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Int Mic Switch" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="Mic Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Mic Jack Switch" val="0"/>
        </path>
      </device>
    </capture>
  </alsa_device>

  <alsa_device name="voice"
               card_id="-1"
               card_name="tegramax98095"
               device_id="2">
    <pcm_config rate="8000"
                channels="1"
                bps="16"
                period_size="256"
                period_count="4"
                start_threshold="1023"
                stop_threshold="1024"
                silence_threshold="0"
                avail_min="1"/>
    <playback>
      <device name="bt-sco"/>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="bt-sco-mic"/>
    </capture>
  </alsa_device>

  <alsa_device name="music"
             card_id="-1"
             card_name="tegraaic326x"
             device_id="0">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>
    <path>
      <!-- playback paths-->
      <ctl name="PCM Playback Volume" val="135"/>
      <ctl name="Speaker Amplifier Volume" val="1"/>
      <ctl name="Receiver Amplifier Volume" val="10"/>
      <ctl name="LOL Output Mixer LDAC Switch" val="1"/>
      <ctl name="LOR Output Mixer RDAC Switch" val="1"/>
      <ctl name="SPKL Output Mixer LOL Volume" val="10"/>
      <ctl name="SPKR Output Mixer LOR Volume" val="10"/>
      <ctl name="REC Output Mixer LOL-B2 Volume" val="10"/>
      <ctl name="REC Output Mixer LOR-B2 Volume" val="10"/>
      <ctl name="HPL Output Mixer LDAC Switch" val="1"/>
      <ctl name="HPR Output Mixer RDAC Switch" val="1"/>
      <!-- capture paths-->
      <ctl name="Left Input Mixer IN2L Switch" val="1"/>
      <ctl name="Right Input Mixer IN2R Switch" val="1"/>
      <ctl name="Left Input Mixer CM1L Switch" val="1"/>
      <ctl name="Right Input Mixer CM1R Switch" val="1"/>
      <ctl name="Mic Bias ext independent enable" val="1"/>
      <ctl name="Input CM mode" val="1"/>
      <ctl name="Left Input Mixer IN1L Switch" val="1"/>
      <ctl name="Left Input Mixer CM1L Switch" val="1"/>
      <ctl name="MICBIAS_EXT ON" val="1"/>
      <ctl name="MICBIAS EXT Power Level" val="0"/>
    </path>

    <playback>
      <device name="headphone">
        <path name="on">
          <ctl name="Headphone Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="Int Spk Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Int Spk Switch" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
          <ctl name="Earpiece Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Earpiece Switch" val="0"/>
        </path>
      </device>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="builtin-mic">
        <path name="on">
          <ctl name="Int Mic Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Int Mic Switch" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="Mic Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Mic Jack Switch" val="0"/>
        </path>
      </device>
    </capture>
  </alsa_device>

  <alsa_device name="voice"
               card_id="-1"
               card_name="tegraaic326x"
               device_id="2">
    <pcm_config rate="8000"
                channels="1"
                bps="16"
                period_size="256"
                period_count="4"
                start_threshold="1023"
                stop_threshold="1024"
                silence_threshold="0"
                avail_min="1"/>
    <playback>
      <device name="bt-sco"/>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="bt-sco-mic"/>
    </capture>
  </alsa_device>
</AudioConfigs>
